#!/usr/bin/env python3
"""Generate port/msg_resource_names.c from PaperBoat's include/assets/messages.h.

PaperBoat stores every game message as a blob called ``messages/MSG_<Name>`` in
its .o2r archives, and resolves a message ID with
``gMsgSectionPaths[msgID >> 16][msgID & 0xFFFF]``.  Language mods built for
PaperBoat replace those blobs by name, so this port needs the same
(section, index) -> name mapping to find them.

The mapping is purely positional, so the table is generated straight from
PaperBoat's header instead of being inferred or typed by hand.

Usage:
    python3 tools/gen_msg_names.py /path/to/PaperBoat/include/assets/messages.h \
        > port/msg_resource_names.c
"""

import re
import sys

PREFIX = "messages/MSG_"


def parse(path):
    text = open(path, encoding="utf-8").read()

    defs = dict(
        re.findall(r'char\s+(gMsg_\w+)\[\]\s*=\s*"__OTR__([^"]+)"', text)
    )
    if not defs:
        sys.exit("error: no gMsg_* string definitions found in " + path)

    sections = {}
    for sec, body in re.findall(
        r"gMsgPaths_sec([0-9A-Fa-f]{2})\[\]\s*=\s*\{(.*?)\};", text, re.S
    ):
        entries = []
        for tok in body.split(","):
            tok = tok.strip()
            if not tok:
                continue
            if tok not in defs:
                sys.exit("error: section %s references unknown symbol %r" % (sec, tok))
            rel = defs[tok]
            if not rel.startswith(PREFIX):
                sys.exit("error: unexpected resource path %r" % rel)
            name = rel[len(PREFIX):]
            if not re.fullmatch(r"[A-Za-z0-9_]+", name):
                sys.exit("error: unexpected characters in resource name %r" % name)
            entries.append(name)
        sections[int(sec, 16)] = entries

    order = re.search(
        r"gMsgSectionPaths\[\]\s*=\s*\{(.*?)\};", text, re.S
    )
    if not order:
        sys.exit("error: gMsgSectionPaths[] not found")
    listed = [
        int(m, 16)
        for m in re.findall(r"gMsgPaths_sec([0-9A-Fa-f]{2})", order.group(1))
    ]
    if listed != list(range(len(listed))):
        sys.exit("error: gMsgSectionPaths is not 00..N in order: %r" % listed)
    if sorted(sections) != listed:
        sys.exit("error: section arrays do not match gMsgSectionPaths")
    return [sections[i] for i in listed]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    sections = parse(sys.argv[1])

    out = []
    w = out.append
    w("/* GENERATED by tools/gen_msg_names.py from PaperBoat's include/assets/messages.h.")
    w(" * Do not edit by hand.  Contains only resource NAMES (metadata), no game data.")
    w(" *")
    w(" * Entry [section][index] is the suffix of the PaperBoat blob")
    w(" * \"messages/MSG_<suffix>\" that holds message ID ((section << 16) | index). */")
    w('#include "msg_override.h"')
    w("")
    for i, names in enumerate(sections):
        w("static const char* const sSec%02X[] = {" % i)
        for n in names:
            w('    "%s",' % n)
        w("};")
        w("")
    w("static const struct { const char* const* names; unsigned count; } sSections[] = {")
    for i, names in enumerate(sections):
        w("    { sSec%02X, %d }," % (i, len(names)))
    w("};")
    w("")
    w("const char* port_msg_resource_suffix(unsigned int msgID) {")
    w("    unsigned int section = msgID >> 16;")
    w("    unsigned int index = msgID & 0xFFFF;")
    w("    if (section >= %d) {" % len(sections))
    w("        return 0;")
    w("    }")
    w("    if (index >= sSections[section].count) {")
    w("        return 0;")
    w("    }")
    w("    return sSections[section].names[index];")
    w("}")
    w("")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
